export const ADD_PRODUCT_TO_CART_REQUSET = "ADD_PRODUCT_TO_CART_REQUSET";
export const ADD_PRODUCT_TO_CART_SUCCESS = "ADD_PRODUCT_TO_CART_SUCCESS";
export const ADD_PRODUCT_TO_CART_FAIL = "ADD_PRODUCT_TO_CART_FAIL";

export const DELETE_PRODUCT_FROM_CART_REQUSET =
    "DELETE_PRODUCT_FROM_CART_REQUSET";
export const DELETE_PRODUCT_FROM_CART_SUCCESS =
    "DELETE_PRODUCT_FROM_CART_SUCCESS";
export const DELETE_PRODUCT_FROM_CART_FAIL = "DELETE_PRODUCT_FROM_CART_FAIL";

export const GET_ALLPRODUCTS_IN_CART_REQUSET =
    "GET_ALLPRODUCTS_IN_CART_REQUSET";
export const GET_ALLPRODUCTS_IN_CART_SUCCESS =
    "GET_ALLPRODUCTS_IN_CART_SUCCESS";
export const GET_ALLPRODUCTS_IN_CART_FAIL = "GET_ALLPRODUCTS_IN_CART_FAIL";
export const RESET_CART = "RESET_CART";
