export const DASHBOARD_ALL_USERS_REQUSET = "DASHBOARD_ALL_USERS_REQUSET";
export const DASHBOARD_ALL_USERS_SUCCESS = "DASHBOARD_ALL_USERS_SUCCESS";
export const DASHBOARD_ALL_USERS_FAIL = "DASHBOARD_ALL_USERS_FAIL";

export const DASHBOARD_USERS_OVERVIEW_REQUSET =
    "DASHBOARD_USERS_OVERVIEW_REQUSET";
export const DASHBOARD_USERS_OVERVIEW_SUCCESS =
    "DASHBOARD_USERS_OVERVIEW_SUCCESS";
export const DASHBOARD_USERS_OVERVIEW_FAIL = "DASHBOARD_USERS_OVERVIEW_FAIL";

export const DASHBOARD_PODUCTS_OVERVIEW_REQUSET =
    "DASHBOARD_PODUCTS_OVERVIEW_REQUSET";
export const DASHBOARD_PODUCTS_OVERVIEW_SUCCESS =
    "DASHBOARD_PODUCTS_OVERVIEW_SUCCESS";
export const DASHBOARD_PODUCTS_OVERVIEW_FAIL =
    "DASHBOARD_PODUCTS_OVERVIEW_FAIL";

export const DASHBOARD_DELETE_USER_USERS_PAGE_REQUSET =
    "DASHBOARD_DELETE_USER_USERS_PAGE_REQUSET";
export const DASHBOARD_DELETE_USER_USERS_PAGE_SUCCESS =
    "DASHBOARD_DELETE_USER_USERS_PAGE_SUCCESS";
export const DASHBOARD_DELETE_USER_USERS_PAGE_FAIL =
    "DASHBOARD_DELETE_USER_USERS_PAGE_FAIL";

export const DASHBOARD_EDIT_USER_USERS_PAGE_REQUSET =
    "DASHBOARD_EDIT_USER_USERS_PAGE_REQUSET";
export const DASHBOARD_EDIT_USER_USERS_PAGE_SUCCESS =
    "DASHBOARD_EDIT_USER_USERS_PAGE_SUCCESS";
export const DASHBOARD_EDIT_USER_USERS_PAGE_FAIL =
    "DASHBOARD_EDIT_USER_USERS_PAGE_FAIL";

export const DASHBOARD_DELETE_PRODUCT_PROCUCTS_PAGE_REQUSET =
    "DASHBOARD_DELETE_PRODUCT_PROCUCTS_PAGE_REQUSET";
export const DASHBOARD_DELETE_PRODUCT_PROCUCTS_PAGE_SUCCESS =
    "DASHBOARD_DELETE_PRODUCT_PROCUCTS_PAGE_SUCCESS";
export const DASHBOARD_DELETE_PRODUCT_PROCUCTS_PAGE_FAIL =
    "DASHBOARD_DELETE_PRODUCT_PROCUCTS_PAGE_FAIL";

export const DASHBOARD_EDIT_PRODUCT_PROCUCTS_PAGE_REQUSET =
    "DASHBOARD_EDIT_PRODUCT_PROCUCTS_PAGE_REQUSET";
export const DASHBOARD_EDIT_PRODUCT_PROCUCTS_PAGE_SUCCESS =
    "DASHBOARD_EDIT_PRODUCT_PROCUCTS_PAGE_SUCCESS";
export const DASHBOARD_EDIT_PRODUCT_PROCUCTS_PAGE_FAIL =
    "DASHBOARD_EDIT_PRODUCT_PROCUCTS_PAGE_FAIL";

export const DASHBOARD_USERS_WANT_TO_BE_SELLERS_REQUSET =
    "DASHBOARD_USERS_WANT_TO_BE_SELLERS_REQUSET";
export const DASHBOARD_USERS_WANT_TO_BE_SELLERS_SUCCESS =
    "DASHBOARD_USERS_WANT_TO_BE_SELLERS_SUCCESS";
export const DASHBOARD_USERS_WANT_TO_BE_SELLERS_FAIL =
    "DASHBOARD_USERS_WANT_TO_BE_SELLERS_FAIL";

export const DASHBOARD_USERS_WANT_TO_BE_SELLERS_NUMBERS_REQUSET =
    "DASHBOARD_USERS_WANT_TO_BE_SELLERS_NUMBERS_REQUSET";
export const DASHBOARD_USERS_WANT_TO_BE_SELLERS_NUMBERS_SUCCESS =
    "DASHBOARD_USERS_WANT_TO_BE_SELLERS_NUMBERS_SUCCESS";
export const DASHBOARD_USERS_WANT_TO_BE_SELLERS_NUMBERS_FAIL =
    "DASHBOARD_USERS_WANT_TO_BE_SELLERS_NUMBERS_FAIL";

export const DASHBOARD_UPDATE_USER_WANT_TO_BE_SELLER_REQUSET =
    "DASHBOARD_UPDATE_USER_WANT_TO_BE_SELLER_REQUSET";
export const DASHBOARD_UPDATE_USER_WANT_TO_BE_SELLER_SUCCESS =
    "DASHBOARD_UPDATE_USER_WANT_TO_BE_SELLER_SUCCESS";
export const DASHBOARD_UPDATE_USER_WANT_TO_BE_SELLER_FAIL =
    "DASHBOARD_UPDATE_USER_WANT_TO_BE_SELLER_FAIL";

export const DASHBOARD_ALL_ORDERS_REQUSET = "DASHBOARD_ALL_ORDERS_REQUSET";
export const DASHBOARD_ALL_ORDERS_SUCCESS = "DASHBOARD_ALL_ORDERS_SUCCESS";
export const DASHBOARD_ALL_ORDERS_FAIL = "DASHBOARD_ALL_ORDERS_FAIL";
