export const CREATE_ORDER_REQUSET = "CREATE_ORDER_REQUSET";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const GET_MY_ORDERS_REQUSET = "GET_MY_ORDERS_REQUSET";
export const GET_MY_ORDERS_SUCCESS = "GET_MY_ORDERS_SUCCESS";
export const GET_MY_ORDERS_FAIL = "GET_MY_ORDERS_FAIL";

export const GET_ORDER_BY_ORDER_ID_REQUSET = "GET_ORDER_BY_ORDER_ID_REQUSET";
export const GET_ORDER_BY_ORDER_ID_SUCCESS = "GET_ORDER_BY_ORDER_ID_SUCCESS";
export const GET_ORDER_BY_ORDER_ID_FAIL = "GET_ORDER_BY_ORDER_ID_FAIL";

export const CREATE_CHECKOUT_SESSION_REQUSET =
    "CREATE_CHECKOUT_SESSION_REQUSET";
export const CREATE_CHECKOUT_SESSION_SUCCESS =
    "CREATE_CHECKOUT_SESSION_SUCCESS";
export const CREATE_CHECKOUT_SESSION_FAIL = "CREATE_CHECKOUT_SESSION_FAIL";

export const UPDATE_ORDER_TO_PAID_REQUSET = "UPDATE_ORDER_TO_PAID_REQUSET";
export const UPDATE_ORDER_TO_PAID_SUCCESS = "UPDATE_ORDER_TO_PAID_SUCCESS";
export const UPDATE_ORDER_TO_PAID_FAIL = "UPDATE_ORDER_TO_PAID_FAIL";

export const UPDATE_ORDER_TO_DELIVERED_REQUSET =
    "UPDATE_ORDER_TO_DELIVERED_REQUSET";
export const UPDATE_ORDER_TO_DELIVERED_SUCCESS =
    "UPDATE_ORDER_TO_DELIVERED_SUCCESS";
export const UPDATE_ORDER_TO_DELIVERED_FAIL = "UPDATE_ORDER_TO_DELIVERED_FAIL";
