export const ALL_PRODUCTS_REQUSET = "ALL_PRODUCTS_REQUSET";
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS";
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL";

export const PRODUCT_DETAILS_REQUSET = "PRODUCT_DETAILS_REQUSET";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const MY_PRODUCTS_REQUEST = "MY_PRODUCTS_REQUEST";
export const MY_PRODUCTS_SUCCESS = "MY_PRODUCTS_SUCCESS";
export const MY_PRODUCTS_FAIL = "MY_PRODUCTS_FAIL";

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";

export const EDIT_MY_PRODUCTS_REQUEST = "EDIT_MY_PRODUCTS_REQUEST";
export const EDIT_MY_PRODUCTS_SUCCESS = "EDIT_MY_PRODUCTS_SUCCESS";
export const EDIT_MY_PRODUCTS_FAIL = "EDIT_MY_PRODUCTS_FAIL";

export const DELETE_MY_PRODUCTS_REQUEST = "DELETE_MY_PRODUCTS_REQUEST";
export const DELETE_MY_PRODUCTS_SUCCESS = "DELETE_MY_PRODUCTS_SUCCESS";
export const DELETE_MY_PRODUCTS_FAIL = "DELETE_MY_PRODUCTS_FAIL";

export const TOP_RATED_BEST_SALE_PRODUCTS_REQUEST =
    "TOP_RATED_BEST_SALE_PRODUCTS_REQUEST";
export const TOP_RATED_BEST_SALE_PRODUCTS_SUCCESS =
    "TOP_RATED_BEST_SALE_PRODUCTS_SUCCESS";
export const TOP_RATED_BEST_SALE_PRODUCTS_FAIL =
    "TOP_RATED_BEST_SALE_PRODUCTS_FAIL";
