export const GET_PRODUCT_REVIEWS_REQUSET = "GET_PRODUCT_REVIEWS_REQUSET";
export const GET_PRODUCT_REVIEWS_SUCCESS = "GET_PRODUCT_REVIEWS_SUCCESS";
export const GET_PRODUCT_REVIEWS_FAIL = "GET_PRODUCT_REVIEWS_FAIL";

export const ADD_PRODUCT_REVIEW_REQUSET = "ADD_PRODUCT_REVIEW_REQUSET";
export const ADD_PRODUCT_REVIEW_SUCCESS = "ADD_PRODUCT_REVIEW_SUCCESS";
export const ADD_PRODUCT_REVIEW_FAIL = "ADD_PRODUCT_REVIEW_FAIL";
export const ADD_PRODUCT_REVIEW_RESET = "ADD_PRODUCT_REVIEW_RESET";

export const EDIT_PRODUCT_REVIEW_REQUSET = "EDIT_PRODUCT_REVIEW_REQUSET";
export const EDIT_PRODUCT_REVIEW_SUCCESS = "EDIT_PRODUCT_REVIEW_SUCCESS";
export const EDIT_PRODUCT_REVIEW_FAIL = "EDIT_PRODUCT_REVIEW_FAIL";
export const EDIT_PRODUCT_REVIEW_RESET = "EDIT_PRODUCT_REVIEW_RESET";

export const DELETE_PRODUCT_REVIEW_REQUSET = "DELETE_PRODUCT_REVIEW_REQUSET";
export const DELETE_PRODUCT_REVIEW_SUCCESS = "DELETE_PRODUCT_REVIEW_SUCCESS";
export const DELETE_PRODUCT_REVIEW_FAIL = "DELETE_PRODUCT_REVIEW_FAIL";
export const DELETE_PRODUCT_REVIEW_RESET = "DELETE_PRODUCT_REVIEW_RESET";

export const GET_MY_REVIEWS_REQUSET = "GET_MY_REVIEWS_REQUSET";
export const GET_MY_REVIEWS_SUCCESS = "GET_MY_REVIEWS_SUCCESS";
export const GET_MY_REVIEWS_FAIL = "GET_MY_REVIEWS_FAIL";
