export const ADD_PRODUCT_TO_WISHLIST_REQUSET =
    "ADD_PRODUCT_TO_WISHLIST_REQUSET";
export const ADD_PRODUCT_TO_WISHLIST_SUCCESS =
    "ADD_PRODUCT_TO_WISHLIST_SUCCESS";
export const ADD_PRODUCT_TO_WISHLIST_FAIL = "ADD_PRODUCT_TO_WISHLIST_FAIL";

export const DELETE_PRODUCT_TO_WISHLIST_REQUSET =
    "DELETE_PRODUCT_TO_WISHLIST_REQUSET";
export const DELETE_PRODUCT_TO_WISHLIST_SUCCESS =
    "DELETE_PRODUCT_TO_WISHLIST_SUCCESS";
export const DELETE_PRODUCT_TO_WISHLIST_FAIL =
    "DELETE_PRODUCT_TO_WISHLIST_FAIL";

export const GET_ALL_PRODUCTS_IN_WISHLIST_REQUSET =
    "GET_ALL_PRODUCTS_IN_WISHLIST_REQUSET";
export const GET_ALL_PRODUCTS_IN_WISHLIST_SUCCESS =
    "GET_ALL_PRODUCTS_IN_WISHLIST_SUCCESS";
export const GET_ALL_PRODUCTS_IN_WISHLIST_FAIL =
    "GET_ALL_PRODUCTS_IN_WISHLIST_FAIL";
export const RESET_WISHLIST = "RESET_WISHLIST";
